@startuml

entity Answer{
    * **a_id: NUMBER**
    * a_t_id: NUMBER
    * a_q_id: NUMBER
    a_answer_text: VARCHAR2
}

entity AnswerOption{
    * **ao_id: NUMBER**
    ao_text: VARCHAR2
    ao_value: NUMBER
    ao_sequenceNumber: NUMBER
}

entity Question{
    * **q_id: NUMBER**
    q_text: VARCHAR2
    q_image: BLOB
    q_seqNo: NUMBER
    q_type: NUMBER
    * q_qn_id: NUMBER
}

entity QuestionType{
    qt_id: NUMBER
    qt_name: VARCHAR2

}

entity Questionnaire{
     * **qn_id: NUMBER**
     qn_name: VARCHAR2
     qn_description: VARCHAR2
}

entity Transaction{
     * **t_id: NUMBER**
     t_transactioncode: VARCHAR2
     t_password: VARCHAR2
     t_is_used: BOOLEAN
     * s_id: NUMBER
}

entity Survey{
     * **s_id: NUMBER**
     * s_t_id: NUMBER
     s_qn_id: NUMBER
     s_date: DATETIME
}

entity ChosenOption {
    *  **co_ao_id: NUMBER**
    * **co_a_id: NUMBER**
}

entity Teacher {
    * **t_id: NUMBER**
    t_name: VARCHAR2
}

Teacher ||.down.|{ Survey
Questionnaire ||.right.|{  Survey
Questionnaire ||.down.|{ Question
Question ||.down.|{ AnswerOption
Survey  ||.down.|{  Transaction
Transaction ||..|{ Answer
Answer ||.left.|{ ChosenOption
AnswerOption ||.right.|{ ChosenOption
Question .right. QuestionType

@enduml

