@startuml

class Survey
class Question
class Questionniere
class User
class Teacher
class Student
class Answer


Survey --> Question
User -left-> Teacher
User --> Student
Teacher -down-> Survey
Student -left-> Survey

@enduml