= questionZ
1.0.0, yyyy-mm-dd: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Pflichtenheft "Was mache ich"


=== Ausgangssituation

Die HTBLA Leonding ist eine Höhere Technische Lehranstalt in der Nähe von Linz.
Der Ausbildungsschwerpunkt der ca. 1000 Schüler ist eine Grundausbildung in der
Informatik mit verschiedenen Spezialisierungen.

=== Istzustand
An der Schule führen Lehrer jedes Semester Umfragen durch um herauszufinden
wie sie ihren Unterricht verbessern können. Diese werden gerade noch auf
Papierbögen ausgefüllt.
Eine andere Möglichkeit ist das Umfragetool der Bundesregierung.

=== Problemstellung
Das Auswerten der Bögen dauert sehr lange und benötigt einen oder mehrere Personen je nach
Teilnehmer und Größe der Umfrage.

Wird das vorhin genannte Tool der Bundesregierung benutzt, bestehen
Datenschutzbedenken.

=== Aufgabenstellung
Es wird ein Softwaresystem erstellt, das es Lehrern erlaubt leicht online Feedbackbögen
zu erstellen welche automatisiert ausgewertet werden soll.

==== Funktionale Anforderungen
* Erstellung von Umfragen
** Fragentypen
*** Mehrfachfragen
*** Einfachfragen
*** Textfragen
*** Ja-Nein-Fragen

* Durchführen von Umfragen
** Beantworten der Fragen
** TAN-Generierung für Schüler

* Auswertung von Umfragen
** visuelle Aufarbeitung der Ergebnisse

==== Nichtfunktionale Anforderungen (NFA)
* Sicherheit
* Effizienz
* Usability
* Portability
* Robustheit
* Benutzbarkeit

=== Ziele
* Vereinfachte und zeitsparende Meinungsforschung
* Höhere Teilnehmerzahlen

=== Mengengerüst
Es gibt ca. 1.000 Schüler an unserer Schule und eine Klasse hat ca. 15 verschiedene Gegenstände.
Wenn pro Jahr 3 Umfragen pro Gegenstand durchgeführt werden, sind das 45.000 Umfragen.

=== Rahmenbedingungen
* Quarkus Backend
* Angular Frontend

== Entwurf "Wie mache ich es"
=== Systemarchitektur
[plantuml,systemarchitektur,png]
----
@startuml

rectangle Browser {
    rectangle "Angular Client (runtime)"
}

rectangle Traefik

Browser <-down- Traefik
Browser -down-> Traefik

package "docker-compose - network" {



    rectangle Quarkus

    rectangle Keycloak

    database database

    rectangle nginx {
        rectangle "Angular Client (to be deployed)"
    }

}

Traefik <-- Quarkus
Traefik --> Quarkus

Keycloak --> Browser
Browser --> Keycloak
nginx --> Browser

@enduml
----
* link:minutes-of-meeting.html[Protokollvorlage]
* link:demo.html[Demo]

